[package]
name = "caldera"
version = "0.1.0"
authors = ["Simon Brown <si@sjbrown.co.uk>"]
edition = "2018"
publish = false

[dependencies]
caldera-macro = { path = "../caldera-macro" }
arrayvec = "0.7"
spark = { git = "https://github.com/sjb3d/spark/" }
spark-imgui = { git = "https://github.com/sjb3d/spark/" }
notify = "4.0"
winit = "0.24"
raw-window-handle = "0.3"
imgui = "0.6.1"
imgui-winit-support = "0.6"
bytemuck = { version = "1.5", features = ["derive"] }
ultraviolet = { version = "0.7.5", features = ["int", "bytemuck"] }
bitvec = "0.20"
structopt = "0.3"
