[package]
name = "caldera-macro"
version = "0.1.0"
authors = ["Simon Brown <si@sjbrown.co.uk>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1.0.15"
syn = "1.0.86"
proc-macro2 = "1.0.36"
